# directory to stored downloaded files
# if you comment this line files will be download in the
# current directory.
baseDir: ./testDir

# canvas authentication information
# This is mandatory.
authentication:
  # canvas api token. Please check this page to see how to get a token.
  # https://github.com/hypothesis/lms/wiki/How-to-Test-the-Canvas-API
  key: YOURKEY
  # your canvas url
  url: https://canvas.ubc.ca/

#### possible unit: MB, GB, KB. No space.

# max file size for a single file
# comment this line to ignore the limitation
maxFileSize: 300MB

# limit of total file size.
# comment this line to ignore the limitation
maxTotalSize: 10GB

# snapshotDir
# snapshot helps you rollback, but occupies extra space.
# comment this line to ignore snapshot
snapshotDir: .snapshot

# enable to allow downloading videos
# need ffmpeg downloaded
allowVideo: false

# enable to allow download link
allowLink: false

# specify stragegy for updating.
# | "newFileOnly"  only download files that is not in current foler.
# | "overwride"    allow overwirte
update: overwirte

# specify the verbosity of logging.
# Three level: mute | verbose | vverbose
verbosity: verbose

#### File list has higher priority than Extension list.
#### White list has higher priority than black list.

courseWhilteList:
  # can be id
  # - 0
  # or course code
  - COSC 211

courseBlackList:
  # - 3
  # - SOCIOLOGY 101

# file name in this list will not be downloaded.
fileBlackList:
  - file1
  - file2

# if this field present, only file name in this list will be
# downloaded.
# white list has higher priority than black list.
fileWhiteList:
  - file3
  - file4
  - Topic2.ExhaustiveGridSearch.pdf

# file types you want to exclude.
# white list has higher priority than black list.
fileExtensionBlackList:
  - go
  - java

# only file types here will downloaded.
fileExtensionWhiteList:
  - pptx
  - jpg
  - pdf
